### ISSUE TITLE
Request: add other tiktok download platform.

### ISSUE THREAD

**Issue by hansputera** [hansputera/tiktok-dl#1]
**TODO:**
- [x] [Tikmate.online](https://tikmate.online)
- [x] [Musically Down](https://musicaldown.com)
- [x] [TTDownloader](https://ttdownloader.com)
- [x] [TTSave](https://ttsave.app)
- [x] [DLTik](https://dltik.com) - @OhYoonHee 
- [x] [SaveFrom](https://id.savefrom.net/19/download-from-tiktok)
